name: ZAP Scan
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ZAP
        run: sudo apt-get install -y zaproxy
      - name: Start ZAP
        run: zap.sh -daemon
      - name: Wait for ZAP to start
        run: sleep 10
      - name: Run ZAP scan
        run: zap-cli --zap-url http://localhost -p 8090 --spider --scan --output /zap/report.html http://
      - name: Save ZAP report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /zap/report.html
