name: ZAP Scan
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          tar -xzf ZAP_2.11.0_Linux.tar.gz
          mv ZAP_2.11.0 /opt/zaproxy
          
      - name: Start ZAP
        run: nohup bash -c '/opt/zaproxy/zap.sh -daemon'&

      - name: Wait for ZAP to start
        run: sleep 10
      - name: Install zap-cli
        run: pip install zapcli

      - name: Run ZAP scan
        run: zap-cli --zap-url http://localhost -p 8090 --quick-scan --output /zap/report.html http://vapi.apisec.ai/vapi
      - name: Save ZAP report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /zap/report.html
